version: "3.8"

services:
  integration-management-be:
    build: .
    container_name: integration-management-be
    image: integration-management-be-image
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_INFO_ENDPOINT=${DB_INFO_ENDPOINT}
      # DO NOT set ORACLE_CLIENT_PATH - let it auto-detect
    volumes:
      # Optional: Only if you need to modify code without rebuilding
      - ./src:/usr/src/app/src
      - ./config:/usr/src/app/config
      # Do NOT mount the entire project as it overrides the container
    restart: unless-stopped